### ISSUE TITLE
it not works!

### ISSUE THREAD

**Issue by xiao-k233** [HobaiRiku/wsl2-auto-portproxy#3]
![image](https://user-images.githubusercontent.com/58621432/204068351-e942383d-1cf4-4596-ac03-dfd6b1b30b82.png)
You can see 21116 port is listening
![image](https://user-images.githubusercontent.com/58621432/204068372-8a0de9a9-2f4b-479e-85f9-7642ba1ae320.png)
but it can't proxy
![image](https://user-images.githubusercontent.com/58621432/204068382-4e68d874-8343-427c-a3ab-74b39a7dfbbc.png)
my .wslconfig
![image](https://user-images.githubusercontent.com/58621432/204068393-824605ca-5d64-4acf-822b-126e14614121.png)
my wsl.conf
WHY????

**Comment by HobaiRiku** [comment]
Working on it

**Comment by HobaiRiku** [comment]
Some things wrong with RegExp in getting Linux's ports I think (but don't know why it works before(⊙_⊙)？). Anyway, I change the way to get Linux's port and change the RegExp, it should work.    
Try this : 
[wslpp_20221130.zip](https://github.com/HobaiRiku/wsl2-auto-portproxy/files/10122744/wslpp_20221130.zip)
And let me know if it works fine in your environment. Thank!

**Comment by xiao-k233** [comment]
> Some things wrong with RegExp in getting Linux's ports I think (but don't know why it works before(⊙_⊙)？). Anyway, I change the way to get Linux's port and change the RegExp, it should work. Try this : [wslpp_20221130.zip](https://github.com/HobaiRiku/wsl2-auto-portproxy/files/10122744/wslpp_20221130.zip) And let me know if it works fine in your environment. Thank! @xiao-k233

Thank！But I am a student from China, I can't use computer on weekdays.So I will test it on weekends.

**Comment by xiao-k233** [comment]
> Some things wrong with RegExp in getting Linux's ports I think (but don't know why it works before(⊙_⊙)？). Anyway, I change the way to get Linux's port and change the RegExp, it should work. Try this : [wslpp_20221130.zip](https://github.com/HobaiRiku/wsl2-auto-portproxy/files/10122744/wslpp_20221130.zip) And let me know if it works fine in your environment. Thank! @xiao-k233

![image](https://user-images.githubusercontent.com/58621432/206829442-9e9ab144-7f97-4f8b-8bdd-215396d4c309.png)
Fantastic！It is working！
